### ISSUE TITLE
Throws error trying to focus SVGElements in Edge

### ISSUE THREAD

**Issue by andrewbranch** [GoogleChrome/inert-polyfill#10]
Microsoft Edge lacks support for `SVGElement.prototype.focus`, so if you have a situation like

```html
<a href="#">Normal link</a>
<a inert href="#">Inert link</a>
<svg tabindex="0" />
```

When you forward-tab from “Normal-link,” the polyfill will try to find the next suitable element to focus and call `element.focus()` on it. So in this case, in Edge, `element.focus` is undefined.

CodePen demo: https://codepen.io/atcb/pen/RLzjPX

I’ve already fixed this in my fork, but didn’t open a PR earlier because my fork exists for the purpose of swapping the attribute trigger from `inert` to `data-inert`, as React <= v15 doesn’t allow passing custom attributes to elements.

Anyway, if you’re interested in accepting a PR, I’ll gladly re-apply my fix to master. My fix is here: https://github.com/andrewbranch/inert-polyfill/commit/88c8e0c68605363dfc99b4f910996ec148660793

**Comment by samthor** [comment]
Yes, please send a PR this way, but we're only interested in keeping the
attribute as "inert" :-) (it's not a custom attribute—it's part of the
spec?)

**Comment by andrewbranch** [comment]
Totally—the `data-inert` was a temporary hack that we needed until we could upgrade to React 16. “Custom attribute” here of course means “anything React doesn’t have whitelisted as a standard attribute.”

Somewhat off-topic: I knew that the concept of inert regions was part of a spec (forget whether it was W3C or WHATWG), but thought that `inert` as an attribute wasn’t actually spec’d yet. If it is, someone ought to add it to React’s whitelist of standard attributes. Can you link to the spec you’re referring to?

**Comment by andrewbranch** [comment]
@samthor sorry for the delay—I work for Microsoft and I’m trying to figure out how/if I can sign the Google CLA for this, and still waiting to hear back. Do you all happen to have a de minimis exception for very small PRs like this that would let me bypass the CLA? Otherwise, I’m afraid this is roadblocked for the moment 😕

**Comment by samthor** [comment]
I've written the patch independently and landed it at HEAD. Can you confirm it works fine?

(I also switched the code to use `TreeWalker`, which I don't know why I didn't do to start with).

**Comment by andrewbranch** [comment]
Yep, it works! https://codepen.io/atcb/pen/wPyQGV

Can we expect a release shortly?

**Comment by samthor** [comment]
Done on GitHub and NPM.
