### ISSUE TITLE
Parents with absolute child are pushed after pressing tab 

### ISSUE THREAD

**Issue by afallaskg** [GoogleChrome/inert-polyfill#12]
Hi there. Hope you are doing fine. So, I'm having this weird problem. Was wondering if this is an issue or do you have a workaround for it. 

Basically,  the problem is that if you have a parent div with position relative and two children. If the second child has the attribute inert set and position=absolute  top = 100% to place it outside the parent, when you change your focus from the first child to an element outside the parent div, the content of the parent is pushed and reveals the second child that should be hidden. 

It is kind of difficult to explain, so I created this code pen: https://codepen.io/afallas9/pen/pKYdgX

One more thing that I didn't mention is that if you are reading the screen with Jaws, and you go through the page with the down arrow key, it still reads the link in the inert div 

Regards

**Comment by samthor** [comment]
To be fair, I don't think this is a problem with [inert]—removing the
attribute in your codepen also reveals the same problem. Of course I am
still confused as to why this is happening.

**Comment by afallaskg** [comment]
@samthor thanks for responding. 

I think that makes sense because if you remove the inert then the link should be focusable. I haven't read the implementation so I'm not sure if the inert is actually preventing the focus or making it jump to the next focusable element.

**Comment by samthor** [comment]
I think this might be because we don't actually stop an inert element from being focused, but instead, kill focus once we detect it.

We cover this in the README, so I don't think we'll ever fix this.
