### ISSUE TITLE
Polyfill Disabling $.on('focus')

### ISSUE THREAD

**Issue by jeffersonmourak** [GoogleChrome/inert-polyfill#3]
When you just add the polyfill on your page this disable the focus on some elements, at now my issue was with `input` element that is not working $.on('focus'), but when i remove the polyfill it back to work again.

**Comment by dustinspecker** [comment]
We just ran into the same problem. Did you happen to figure out a solution while still using this polyfill?

**Comment by samthor** [comment]
I've removed the offending lines which are preventing this! Look out for 0.2.3 in a few minutes.

**Comment by jeffersonmourak** [comment]
Cool, thanks :D
