### ISSUE TITLE
Causing issues with firefox input/textarea

### ISSUE THREAD

**Issue by tnrich** [GoogleChrome/inert-polyfill#4]
I am having trouble with inert polyfill screwing up firefox textareas/inputs (the cursor doesn't show up and highlighting doesn't work). Here is a small requirebin of what is happening:

http://requirebin.com/?gist=915d1c6c0b273dc1eff9c201c0943968

view it on chrome and firefox and see the difference for yourselves. 

It would be much appreciated if this could be fixed because it is otherwise totally awesome!

Thanks!

**Comment by tnrich** [comment]
@samthor any thoughts on this issue? Will this ever be fixed? Can anyone confirm that this is indeed an issue?

**Comment by shannonmoeller** [comment]
Confirmed. Just got bit by the same bug.

**Edit:** Found a workaround: https://github.com/WICG/inert

**Comment by samthor** [comment]
I've fixed this now. Look out for 0.2.3 in a few minutes!
