### ISSUE TITLE
Inert elements are searchable in browser search

### ISSUE THREAD

**Issue by boyum** [GoogleChrome/inert-polyfill#9]
If I understand the inert property correctly, apart from actually rendering, the element should appear as if `display: none` was active. The browser search function (cmd/ctrl+f) does not list hidden elements, but it does list `inert` ones. This is the native behaviour of Chrome Canary as well, but after a [quick chat with Rob Dodson and Alice Boxhall](https://twitter.com/sundress/status/884884758399827968), this should perhaps be fixed there as well.

As for a solution to this problem, I'm not of much help. The only text I can think of that isn't searchable is that added as CSS `content`. To remove the text from the DOM to put it in the content I guess would trigger a repaint, which would render the inert property useless in many cases.

A quick demo: https://codepen.io/sindre/pen/BZGbrK

**Comment by samthor** [comment]
It's a good thought, but except for the simplest of `inert` elements, I don't think it's practical to move all the content into pseudo-elements :)

So this bug is obviously something that can be fixed natively, but I think it's probably not going to be possible for the polyfill.

**Comment by samthor** [comment]
~years later, we are not going to solve this.
